version: "3"

services:
  web:
    image: ${DTR_URL}/demo/hello-world-python:${TAG}
    ports:
     - "80:5000"
    networks:
      - hello-world


  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes
    networks:
      - hello-world
    volumes:
      - redis-data:/data


networks:
  hello-world:


volumes:
  redis-data:

